export const roles = Object.freeze({
  SUPER_ADMIN: "SUPER_ADMIN",
  UNIVERSITY_ADMIN: "UNIVERSITY_ADMIN",
  UNIVERSITY_STAFF: "UNIVERSITY_STAFF",
  STUDENT: "STUDENT",
  EMPLOYER: "EMPLOYER",
  AUDITOR: "AUDITOR",
});

